path :- app/design/frontend/Plumtree/everlast/Magento_Catalog/templates/product/list.phtml

<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
    $plumtreeHelper = $this->helper('Plumtree\Homepage\Helper\Data');
    $currentCategory = $plumtreeHelper->getCurrentCategory();
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_productCollection->setFlag('has_stock_status_filter', true);
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
    <?php
    if ($currentCategory->getDescription()) {
    echo $currentCategory->getDescription();
    }
    ?>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();

    ?>
    <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>" itemscope itemtype="http://schema.org/ItemList">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
		<?php 
		$_iterator = 1; 
		foreach ($_productCollection as $_product): 
		?>
            <?php
                // echo "<pre>";
                //  print_r($_product->getData());
                //  echo "</pre>";
                // //  echo "<br>";
                //  exit();
              $productDetails = $block->getLayout()->createBlock('Plumtree\CatalogExtended\Block\Product\Details');
              $productId = $_product->getId();
              $productType = $_product->getTypeId();
            ?>
            <li class="item product product-item" itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">

                <meta itemprop="position" content="<?php echo $_iterator++; ?>" />
                <link itemprop="url" href="<?php echo $_product->getProductUrl(); ?>" />
                <div class="product-item-info" data-container="product-<?= /* @escapeNotVerified */ $viewMode ?>">
				<?php
                //Sale Label
                $specialprice = $_product->getSpecialPrice();
                $specialPriceFromDate = $_product->getSpecialFromDate();
                $specialPriceToDate = $_product->getSpecialToDate();
                $today =  time();

                if($_product->getExcludeTag()){
                    echo "<div class='promo'>EXC. FROM PROMO'S</div>";
                } else if ($specialprice && ($_product->getPrice()>$_product->getFinalPrice())) {
                    if($today >= strtotime( $specialPriceFromDate) && $today <= strtotime($specialPriceToDate) ||
                        $today >= strtotime( $specialPriceFromDate) && is_null($specialPriceToDate)): ?>
                            <div class="sale-lable"><?php echo __('Sale'); ?></div>
                    <?php endif;
                } ?>
                    <?php //Limited Edition Label
                    if($_product->getLimitedEdition()): ?>
                        <div class="sale-lable sale-ltd limited">
                            <?php 
                            // echo $_product->getLimitedEdition();
                            echo __('Limited'); ?>
                        </div>
                    <?php endif; ?>

                

            <?php if ($_product->getCustomlayout()): ?>
                    <?php //Doogma CustomLayout Label
                    // if($_product->getCustomlayout()): ?>
                        <div class="sale-lable sale-ltd customlayout"> 
                      <img src="<?php  echo $block->getViewFileUrl('images/CustomizerPenIcon.png'); ?>" alt="pen"> 
                        
                            <?php 
                            echo $_product->getCustomlayout();
                            //  echo $_product->getCustomLayout();
                            echo __('Penn'); ?>
                        </div>
                    <?php endif; ?>

                    <?php //New Label ?>

                    <?php if($plumtreeHelper->isProductNew($_product)): ?>
                        <div class="new-lable">
                            <?php echo __('New'); ?>
                        </div>
                    <?php endif; ?>
                    <?php
                    $productImage = $block->getImage($_product, $imageDisplayArea);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>

                    <a aria-label="product-item-photo" href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
		     <?= $productImage->toHtml() ?>
                    </a>
                    <meta itemprop="sku" content="<?php echo $_product->getSku(); ?>" />
                    <div itemprop="brand" itemtype="http://schema.org/Brand" itemscope>
                      <meta itemprop="name" content="Everlast" />
                    </div>
                    <meta itemprop="description" content="<?php echo $_product->getDescription(); ?>" />
                    <div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                      <?php if ($_product->isAvailable()): ?>
                        <meta itemprop="availability" content="https://schema.org/InStock" />
                      <?php else: ?>
                        <meta itemprop="availability" content="https://schema.org/OutOfStock" />
                      <?php endif; ?>
                      <meta itemprop="priceCurrency" content="USD" />
                      <meta itemprop="price" content="<?php echo $_product->getFinalPrice(); ?>" />
                    </div>
                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <?php
                        if($currentCategory){
                            if($currentCategory->getName() == 'Undefeated Collection'){ ?>
                                <span style="display: none;" class="undefeated-category-name"><?php echo $currentCategory->getName(); ?></span>
                            <?php }
                        } ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                <span itemprop="name"><?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?></span>
                            </a>
                        </strong>

                        <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                        <?php if($_product->isSalable()): ?>
                          <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
                        <?php else: ?>
                          <?php
                          $priceHelper = $this->helper('Magento\Framework\Pricing\Helper\Data');
                          if($productType == 'configurable'){
                            list($finalPrice, $regularPrice) = $productDetails->getChildMinPrice($productId);
                          }else{
                            $finalPrice = $_product->getPriceInfo()->getPrice('final_price')->getAmount()->getBaseAmount();
                            $regularPrice = $_product->getPriceInfo()->getPrice('regular_price')->getAmount()->getBaseAmount();
                          }

                          $specialPrice = $priceHelper->currency($finalPrice, true, false);
                          $oldPrice = $priceHelper->currency($regularPrice, true, false);
                          ?>
                          <div class="price-box price-final_price">
                            <?php if($productType == 'configurable'):?>
                              <span class="title">As low as:</span>
                            <?php endif; ?>
                            <span class="normal-price">
                                <span class="price-container price-final_price">
                                    <span class="price-wrapper "><span class="price"><?= $specialPrice?></span></span>
                                </span>
                            </span>
                            <?php if($regularPrice > $finalPrice): ?>
                              <span class="old-price sly-old-price">
                                <span class="price-container price-final_price tax weee">
                                  <span class="price-wrapper "><span class="price"><?= $oldPrice?></span></span>
                                </span>
                              </span>
                            <?php endif; ?>
                          </div>
                        <?php endif;?>
                        <?php if($productType == 'configurable'): ?>
                        <div class="attribute_count">
                          <?php
                          $colorCount = $productDetails->getChildAttributeCount($productId, 'color');
                          if($colorCount){
                            if($colorCount == 1) echo " | ".$colorCount." Color";
                            if($colorCount > 1) echo " | ".$colorCount." Colors";
                          }
                          ?>
                        </div>
                      <?php endif; ?>

                        <div class="product-item-inner">
                            <?php if(!$_product->getOfflineOnly()): ?>
                            	<?= $block->getProductDetailsHtml($_product) ?>
                                    <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                        <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                            <?php if ($_product->isSaleable()): ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                                    <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                                    <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                    <?= $block->getBlockHtml('formkey') ?>
                                                    <button type="submit"
                                                            title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                            class="action tocart primary">
                                                        <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                    </button>
                                                </form>
                                            <?php else: ?>
                                                <?php if ($_product->isAvailable()): ?>
                                                    <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                        <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                            <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                                <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                <?php if ($showDescription):?>
                                    <div class="product description product-item-description">
                                        <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                        <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" title="<?= /* @escapeNotVerified */ $_productNameStripped ?>"
                                           class="action more"><?= /* @escapeNotVerified */ __('Learn More') ?></a>
                                    </div>
                                <?php endif; ?>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>

<?php
$urlInterface = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Framework\App\Response\RedirectInterface');
    $previousURL = $urlInterface->getRefererUrl();
    if (strpos($previousURL, 'glovefinder') == true) {
        echo '<div class="glove-find-btn"><span class="looking-for">Didn’t find what you wanted?</span><a href="/glovefinder">TRY AGAIN</a></div>';
    }
    ?>
<script>
/*require(['jquery', 'jquery/ui'], function($){
	jQuery('div.filter-current').addClass('active');
	jQuery('li.item.product.product-item').click(function(){
		var selected_color = jQuery(this).find('div.swatch-attribute.color').attr('option-selected');
		var selected_size = jQuery(this).find('div.swatch-attribute.size').attr('option-selected');
		jQuery(this).find("div.promo").hide();
		jQuery(this).find("div.promo."+selected_color+selected_size).show();
	});
});	*/
</script>
