<?php  //echo phpinfo() ?>
<script src="https://cdn-widgetsrepository.yotpo.com/v1/loader/EcDGYsc1sBq6nh_q6f0P3w" async></script>

<?php
// echo "Hiiii";
// echo $block->getClass(); exit();
// $enabledCustomerGroupsCsv = $this->scopeConfig
            //   ->getValue('section_id/general/customer_group_list');

        // If any groups have been configured
        // if ($enabledCustomerGroupsCsv) {
            // Convert CSV into array
            // $enabledCustomerGroupIds = explode(',', $enabledCustomerGroupsCsv);
// ?>
            <div class="yotpo-widget-instance" data-yotpo-instance-id="95350"></div>

    <!-- <?php //   } -->

// ?>
